name: CICD

on:
  push:
    branches:
      - master
      - ubuntu

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Build Docker Image (Development)
        run: docker build -t integrationninjas/reactjs-app:dev --target dev .

      - name: Build Docker Image (Production)
        run: docker build -t integrationninjas/reactjs-app:prod --target prod .

  deploy-dev: 
    needs: build
    runs-on: self-hosted
    steps:
      - name: Delete Old Dev Container
        run: docker rm -f reactContainer-dev || true

      - name: Run Docker Container (Development)
        run: docker run -d -p 3000:3000 --name reactContainer-dev integrationninjas/reactjs-app:dev npm start

  deploy-prod: 
    needs: build
    runs-on: self-hosted
    steps:
      - name: Delete Old Prod Container
        run: docker rm -f reactContainer-prod || true

      - name: Run Docker Container (Production)
        run: docker run -d -p 3000:3000 --name reactContainer-prod integrationninjas/reactjs-app:prod npm run serve


        
